name: Python package

on: [push]

env:
  UNITTEST_RUN_SLOW_TESTS: "1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg espeak-ng
          python -m pip install --upgrade pip
          # FIXME: `tgt` is temporarily installed since tests break without it.
          # Consider adding it as a hard dependency or ignore(skip) in tests if it is not installed intead of failing.
          pip install -r requirements.txt tgt
      - name: Tests
        run: |
          python -m unittest discover -v
